// <auto-generated />
using CardStocksWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CardStocksWebsite.Migrations
{
    [DbContext(typeof(CardStocksWebsiteContext))]
    [Migration("20171019104942_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardStocksWebsite.Models.Card", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Color");

                    b.Property<string>("Condition");

                    b.Property<string>("Name");

                    b.Property<string>("Rarity");

                    b.Property<double>("Recommended_Price");

                    b.Property<string>("Set");

                    b.HasKey("ID");

                    b.ToTable("Card");
                });
#pragma warning restore 612, 618
        }
    }
}
